<?php

class m140114_185347_countries extends CDbMigration
{
	public function up()
	{
        $this->createTable('countries', array(
            'id'         => 'pk',
            'code2'      => 'CHAR(2) NOT NULL',
            'code3'      => 'CHAR(3) NOT NULL',
            'name'       => 'VARCHAR(128) NOT NULL',
            'name_en'    => 'VARCHAR(128) NOT NULL',
        ));

        $this->execute("
            INSERT INTO countries (`name`, `name_en`, `code2`, `code3`) VALUES
            ('Абхазия', 'Abkhazia', 'AB', 'ABH'),
            ('Австралия', 'Australia', 'AU', 'AUS'),
            ('Австрия', 'Austria', 'AT', 'AUT'),
            ('Азербайджан', 'Azerbaijan', 'AZ', 'AZE'),
            ('Албания', 'Albania', 'AL', 'ALB'),
            ('Алжир', 'Algeria', 'DZ', 'DZA'),
            ('Американское Самоа', 'American Samoa', 'AS', 'ASM'),
            ('Ангилья', 'Anguilla', 'AI', 'AIA'),
            ('Ангола', 'Angola', 'AO', 'AGO'),
            ('Андорра', 'Andorra', 'AD', 'AND'),
            ('Антарктида', 'Antarctica', 'AQ', 'ATA'),
            ('Антигуа и Барбуда', 'Antigua and Barbuda', 'AG', 'ATG'),
            ('Аргентина', 'Argentina', 'AR', 'ARG'),
            ('Армения', 'Armenia', 'AM', 'ARM'),
            ('Аруба', 'Aruba', 'AW', 'ABW'),
            ('Афганистан', 'Afghanistan', 'AF', 'AFG'),
            ('Багамы', 'Bahamas', 'BS', 'BHS'),
            ('Бангладеш', 'Bangladesh', 'BD', 'BGD'),
            ('Барбадос', 'Barbados', 'BB', 'BRB'),
            ('Бахрейн', 'Bahrain', 'BH', 'BHR'),
            ('Беларусь', 'Belarus', 'BY', 'BLR'),
            ('Белиз', 'Belize', 'BZ', 'BLZ'),
            ('Бельгия', 'Belgium', 'BE', 'BEL'),
            ('Бенин', 'Benin', 'BJ', 'BEN'),
            ('Бермуды', 'Bermuda', 'BM', 'BMU'),
            ('Болгария', 'Bulgaria', 'BG', 'BGR'),
            ('Боливия, Многонациональное Государство', 'Bolivia, plurinational state of', 'BO', 'BOL'),
            ('Бонайре, Саба и Синт-Эстатиус', 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES'),
            ('Босния и Герцеговина', 'Bosnia and Herzegovina', 'BA', 'BIH'),
            ('Ботсвана', 'Botswana', 'BW', 'BWA'),
            ('Бразилия', 'Brazil', 'BR', 'BRA'),
            ('Британская территория в Индийском океане', 'British Indian Ocean Territory', 'IO', 'IOT'),
            ('Бруней-Даруссалам', 'Brunei Darussalam', 'BN', 'BRN'),
            ('Буркина-Фасо', 'Burkina Faso', 'BF', 'BFA'),
            ('Бурунди', 'Burundi', 'BI', 'BDI'),
            ('Бутан', 'Bhutan', 'BT', 'BTN'),
            ('Вануату', 'Vanuatu', 'VU', 'VUT'),
            ('Венгрия', 'Hungary', 'HU', 'HUN'),
            ('Венесуэла Боливарианская Республика', 'Venezuela', 'VE', 'VEN'),
            ('Виргинские острова, Британские', 'Virgin Islands, British', 'VG', 'VGB'),
            ('Виргинские острова, США', 'Virgin Islands, U.S.', 'VI', 'VIR'),
            ('Вьетнам', 'Vietnam', 'VN', 'VNM'),
            ('Габон', 'Gabon', 'GA', 'GAB'),
            ('Гаити', 'Haiti', 'HT', 'HTI'),
            ('Гайана', 'Guyana', 'GY', 'GUY'),
            ('Гамбия', 'Gambia', 'GM', 'GMB'),
            ('Гана', 'Ghana', 'GH', 'GHA'),
            ('Гваделупа', 'Guadeloupe', 'GP', 'GLP'),
            ('Гватемала', 'Guatemala', 'GT', 'GTM'),
            ('Гвинея', 'Guinea', 'GN', 'GIN'),
            ('Гвинея-Бисау', 'Guinea-Bissau', 'GW', 'GNB'),
            ('Германия', 'Germany', 'DE', 'DEU'),
            ('Гернси', 'Guernsey', 'GG', 'GGY'),
            ('Гибралтар', 'Gibraltar', 'GI', 'GIB'),
            ('Гондурас', 'Honduras', 'HN', 'HND'),
            ('Гонконг', 'Hong Kong', 'HK', 'HKG'),
            ('Гренада', 'Grenada', 'GD', 'GRD'),
            ('Гренландия', 'Greenland', 'GL', 'GRL'),
            ('Греция', 'Greece', 'GR', 'GRC'),
            ('Грузия', 'Georgia', 'GE', 'GEO'),
            ('Гуам', 'Guam', 'GU', 'GUM'),
            ('Дания', 'Denmark', 'DK', 'DNK'),
            ('Джерси', 'Jersey', 'JE', 'JEY'),
            ('Джибути', 'Djibouti', 'DJ', 'DJI'),
            ('Доминика', 'Dominica', 'DM', 'DMA'),
            ('Доминиканская Республика', 'Dominican Republic', 'DO', 'DOM'),
            ('Египет', 'Egypt', 'EG', 'EGY'),
            ('Замбия', 'Zambia', 'ZM', 'ZMB'),
            ('Западная Сахара', 'Western Sahara', 'EH', 'ESH'),
            ('Зимбабве', 'Zimbabwe', 'ZW', 'ZWE'),
            ('Израиль', 'Israel', 'IL', 'ISR'),
            ('Индия', 'India', 'IN', 'IND'),
            ('Индонезия', 'Indonesia', 'ID', 'IDN'),
            ('Иордания', 'Jordan', 'JO', 'JOR'),
            ('Ирак', 'Iraq', 'IQ', 'IRQ'),
            ('Иран, Исламская Республика', 'Iran, Islamic Republic of', 'IR', 'IRN'),
            ('Ирландия', 'Ireland', 'IE', 'IRL'),
            ('Исландия', 'Iceland', 'IS', 'ISL'),
            ('Испания', 'Spain', 'ES', 'ESP'),
            ('Италия', 'Italy', 'IT', 'ITA'),
            ('Йемен', 'Yemen', 'YE', 'YEM'),
            ('Кабо-Верде', 'Cape Verde', 'CV', 'CPV'),
            ('Казахстан', 'Kazakhstan', 'KZ', 'KAZ'),
            ('Камбоджа', 'Cambodia', 'KH', 'KHM'),
            ('Камерун', 'Cameroon', 'CM', 'CMR'),
            ('Канада', 'Canada', 'CA', 'CAN'),
            ('Катар', 'Qatar', 'QA', 'QAT'),
            ('Кения', 'Kenya', 'KE', 'KEN'),
            ('Кипр', 'Cyprus', 'CY', 'CYP'),
            ('Киргизия', 'Kyrgyzstan', 'KG', 'KGZ'),
            ('Кирибати', 'Kiribati', 'KI', 'KIR'),
            ('Китай', 'China', 'CN', 'CHN'),
            ('Кокосовые (Килинг) острова', 'Cocos (Keeling) Islands', 'CC', 'CCK'),
            ('Колумбия', 'Colombia', 'CO', 'COL'),
            ('Коморы', 'Comoros', 'KM', 'COM'),
            ('Конго', 'Congo', 'CG', 'COG'),
            ('Конго, Демократическая Республика', 'Congo, Democratic Republic of the', 'CD', 'COD'),
            ('Корея, Народно-Демократическая Республика', 'Korea, Democratic People s republic of', 'KP', 'PRK'),
            ('Корея, Республика', 'Korea, Republic of', 'KR', 'KOR'),
            ('Коста-Рика', 'Costa Rica', 'CR', 'CRI'),
            ('Кот д Ивуар', 'Cote d Ivoire', 'CI', 'CIV'),
            ('Куба', 'Cuba', 'CU', 'CUB'),
            ('Кувейт', 'Kuwait', 'KW', 'KWT'),
            ('Кюрасао', 'Curacao', 'CW', 'CUW'),
            ('Лаос', 'Lao People s Democratic Republic', 'LA', 'LAO'),
            ('Латвия', 'Latvia', 'LV', 'LVA'),
            ('Лесото', 'Lesotho', 'LS', 'LSO'),
            ('Ливан', 'Lebanon', 'LB', 'LBN'),
            ('Ливийская Арабская Джамахирия', 'Libyan Arab Jamahiriya', 'LY', 'LBY'),
            ('Либерия', 'Liberia', 'LR', 'LBR'),
            ('Лихтенштейн', 'Liechtenstein', 'LI', 'LIE'),
            ('Литва', 'Lithuania', 'LT', 'LTU'),
            ('Люксембург', 'Luxembourg', 'LU', 'LUX'),
            ('Маврикий', 'Mauritius', 'MU', 'MUS'),
            ('Мавритания', 'Mauritania', 'MR', 'MRT'),
            ('Мадагаскар', 'Madagascar', 'MG', 'MDG'),
            ('Майотта', 'Mayotte', 'YT', 'MYT'),
            ('Макао', 'Macao', 'MO', 'MAC'),
            ('Малави', 'Malawi', 'MW', 'MWI'),
            ('Малайзия', 'Malaysia', 'MY', 'MYS'),
            ('Мали', 'Mali', 'ML', 'MLI'),
            ('Малые Тихоокеанские отдаленные острова Соединенных Штатов', 'United States Minor Outlying Islands', 'UM', 'UMI'),
            ('Мальдивы', 'Maldives', 'MV', 'MDV'),
            ('Мальта', 'Malta', 'MT', 'MLT'),
            ('Марокко', 'Morocco', 'MA', 'MAR'),
            ('Мартиника', 'Martinique', 'MQ', 'MTQ'),
            ('Маршалловы острова', 'Marshall Islands', 'MH', 'MHL'),
            ('Мексика', 'Mexico', 'MX', 'MEX'),
            ('Микронезия, Федеративные Штаты', 'Micronesia, Federated States of', 'FM', 'FSM'),
            ('Мозамбик', 'Mozambique', 'MZ', 'MOZ'),
            ('Молдова, Республика', 'Moldova', 'MD', 'MDA'),
            ('Монако', 'Monaco', 'MC', 'MCO'),
            ('Монголия', 'Mongolia', 'MN', 'MNG'),
            ('Монтсеррат', 'Montserrat', 'MS', 'MSR'),
            ('Мьянма', 'Burma', 'MM', 'MMR'),
            ('Намибия', 'Namibia', 'NA', 'NAM'),
            ('Науру', 'Nauru', 'NR', 'NRU'),
            ('Непал', 'Nepal', 'NP', 'NPL'),
            ('Нигер', 'Niger', 'NE', 'NER'),
            ('Нигерия', 'Nigeria', 'NG', 'NGA'),
            ('Нидерланды', 'Netherlands', 'NL', 'NLD'),
            ('Никарагуа', 'Nicaragua', 'NI', 'NIC'),
            ('Ниуэ', 'Niue', 'NU', 'NIU'),
            ('Новая Зеландия', 'New Zealand', 'NZ', 'NZL'),
            ('Новая Каледония', 'New Caledonia', 'NC', 'NCL'),
            ('Норвегия', 'Norway', 'NO', 'NOR'),
            ('Объединенные Арабские Эмираты', 'United Arab Emirates', 'AE', 'ARE'),
            ('Оман', 'Oman', 'OM', 'OMN'),
            ('Остров Буве', 'Bouvet Island', 'BV', 'BVT'),
            ('Остров Мэн', 'Isle of Man', 'IM', 'IMN'),
            ('Остров Норфолк', 'Norfolk Island', 'NF', 'NFK'),
            ('Остров Рождества', 'Christmas Island', 'CX', 'CXR'),
            ('Остров Херд и острова Макдональд', 'Heard Island and McDonald Islands', 'HM', 'HMD'),
            ('Острова Кайман', 'Cayman Islands', 'KY', 'CYM'),
            ('Острова Кука', 'Cook Islands', 'CK', 'COK'),
            ('Острова Теркс и Кайкос', 'Turks and Caicos Islands', 'TC', 'TCA'),
            ('Пакистан', 'Pakistan', 'PK', 'PAK'),
            ('Палау', 'Palau', 'PW', 'PLW'),
            ('Палестинская территория, оккупированная', 'Palestinian Territory, Occupied', 'PS', 'PSE'),
            ('Панама', 'Panama', 'PA', 'PAN'),
            ('Папуа-Новая Гвинея', 'Papua New Guinea', 'PG', 'PNG'),
            ('Парагвай', 'Paraguay', 'PY', 'PRY'),
            ('Перу', 'Peru', 'PE', 'PER'),
            ('Питкерн', 'Pitcairn', 'PN', 'PCN'),
            ('Польша', 'Poland', 'PL', 'POL'),
            ('Португалия', 'Portugal', 'PT', 'PRT'),
            ('Пуэрто-Рико', 'Puerto Rico', 'PR', 'PRI'),
            ('Республика Македония', 'Macedonia, The Former Yugoslab Republic Of', 'MK', 'MKD'),
            ('Реюньон', 'Reunion', 'RE', 'REU'),
            ('Россия', 'Russian Federation', 'RU', 'RUS'),
            ('Руанда', 'Rwanda', 'RW', 'RWA'),
            ('Румыния', 'Romania', 'RO', 'ROU'),
            ('Самоа', 'Samoa', 'WS', 'WSM'),
            ('Сан-Марино', 'San Marino', 'SM', 'SMR'),
            ('Сан-Томе и Принсипи', 'Sao Tome and Principe', 'ST', 'STP'),
            ('Саудовская Аравия', 'Saudi Arabia', 'SA', 'SAU'),
            ('Свазиленд', 'Swaziland', 'SZ', 'SWZ'),
            ('Святая Елена, Остров вознесения, Тристан-да-Кунья', 'Saint Helena, Ascension And Tristan Da Cunha', 'SH', 'SHN'),
            ('Северные Марианские острова', 'Northern Mariana Islands', 'MP', 'MNP'),
            ('Сен-Бартельми', 'Saint Barthelemy', 'BL', 'BLM'),
            ('Сен-Мартен', 'Saint Martin (French Part)', 'MF', 'MAF'),
            ('Сенегал', 'Senegal', 'SN', 'SEN'),
            ('Сент-Винсент и Гренадины', 'Saint Vincent and the Grenadines', 'VC', 'VCT'),
            ('Сент-Китс и Невис', 'Saint Kitts and Nevis', 'KN', 'KNA'),
            ('Сент-Люсия', 'Saint Lucia', 'LC', 'LCA'),
            ('Сент-Пьер и Микелон', 'Saint Pierre and Miquelon', 'PM', 'SPM'),
            ('Сербия', 'Serbia', 'RS', 'SRB'),
            ('Сейшелы', 'Seychelles', 'SC', 'SYC'),
            ('Сингапур', 'Singapore', 'SG', 'SGP'),
            ('Синт-Мартен', 'Sint Maarten', 'SX', 'SXM'),
            ('Сирийская Арабская Республика', 'Syrian Arab Republic', 'SY', 'SYR'),
            ('Словакия', 'Slovakia', 'SK', 'SVK'),
            ('Словения', 'Slovenia', 'SI', 'SVN'),
            ('Соединенное Королевство', 'United Kingdom', 'GB', 'GBR'),
            ('Соединенные Штаты', 'United States', 'US', 'USA'),
            ('Соломоновы острова', 'Solomon Islands', 'SB', 'SLB'),
            ('Сомали', 'Somalia', 'SO', 'SOM'),
            ('Судан', 'Sudan', 'SD', 'SDN'),
            ('Суринам', 'Suriname', 'SR', 'SUR'),
            ('Сьерра-Леоне', 'Sierra Leone', 'SL', 'SLE'),
            ('Таджикистан', 'Tajikistan', 'TJ', 'TJK'),
            ('Таиланд', 'Thailand', 'TH', 'THA'),
            ('Тайвань (Китай)', 'Taiwan, Province of China', 'TW', 'TWN'),
            ('Танзания, Объединенная Республика', 'Tanzania, United Republic Of', 'TZ', 'TZA'),
            ('Тимор-Лесте', 'Timor-Leste', 'TL', 'TLS'),
            ('Того', 'Togo', 'TG', 'TGO'),
            ('Токелау', 'Tokelau', 'TK', 'TKL'),
            ('Тонга', 'Tonga', 'TO', 'TON'),
            ('Тринидад и Тобаго', 'Trinidad and Tobago', 'TT', 'TTO'),
            ('Тувалу', 'Tuvalu', 'TV', 'TUV'),
            ('Тунис', 'Tunisia', 'TN', 'TUN'),
            ('Туркмения', 'Turkmenistan', 'TM', 'TKM'),
            ('Турция', 'Turkey', 'TR', 'TUR'),
            ('Уганда', 'Uganda', 'UG', 'UGA'),
            ('Узбекистан', 'Uzbekistan', 'UZ', 'UZB'),
            ('Украина', 'Ukraine', 'UA', 'UKR'),
            ('Уоллис и Футуна', 'Wallis and Futuna', 'WF', 'WLF'),
            ('Уругвай', 'Uruguay', 'UY', 'URY'),
            ('Фарерские острова', 'Faroe Islands', 'FO', 'FRO'),
            ('Фиджи', 'Fiji', 'FJ', 'FJI'),
            ('Филиппины', 'Philippines', 'PH', 'PHL'),
            ('Финляндия', 'Finland', 'FI', 'FIN'),
            ('Фолклендские острова (Мальвинские)', 'Falkland Islands (Malvinas)', 'FK', 'FLK'),
            ('Франция', 'France', 'FR', 'FRA'),
            ('Французская Гвиана', 'French Guiana', 'GF', 'GUF'),
            ('Французская Полинезия', 'French Polynesia', 'PF', 'PYF'),
            ('Французские Южные территории', 'French Southern Territories', 'TF', 'ATF'),
            ('Хорватия', 'Croatia', 'HR', 'HRV'),
            ('Центрально-Африканская Республика', 'Central African Republic', 'CF', 'CAF'),
            ('Чад', 'Chad', 'TD', 'TCD'),
            ('Черногория', 'Montenegro', 'ME', 'MNE'),
            ('Чешская Республика', 'Czech Republic', 'CZ', 'CZE'),
            ('Чили', 'Chile', 'CL', 'CHL'),
            ('Швейцария', 'Switzerland', 'CH', 'CHE'),
            ('Швеция', 'Sweden', 'SE', 'SWE'),
            ('Шпицберген и Ян Майен', 'Svalbard and Jan Mayen', 'SJ', 'SJM'),
            ('Шри-Ланка', 'Sri Lanka', 'LK', 'LKA'),
            ('Эквадор', 'Ecuador', 'EC', 'ECU'),
            ('Экваториальная Гвинея', 'Equatorial Guinea', 'GQ', 'GNQ'),
            ('Эландские острова', 'Aland Islands', 'AX', 'ALA'),
            ('Эль-Сальвадор', 'El Salvador', 'SV', 'SLV'),
            ('Эритрея', 'Eritrea', 'ER', 'ERI'),
            ('Эстония', 'Estonia', 'EE', 'EST'),
            ('Эфиопия', 'Ethiopia', 'ET', 'ETH'),
            ('Южная Африка', 'South Africa', 'ZA', 'ZAF'),
            ('Южная Джорджия и Южные Сандвичевы острова', 'South Georgia and the South Sandwich Islands', 'GS', 'SGS'),
            ('Южная Осетия', 'South Ossetia', 'OS', 'OST'),
            ('Южный Судан', 'South Sudan', 'SS', 'SSD'),
            ('Ямайка', 'Jamaica', 'JM', 'JAM'),
            ('Япония', 'Japan', 'JP', 'JPN');
        ");
	}

	public function down()
	{
		$this->dropTable('countries');
	}
}